In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

%matplotlib inline

In [4]:
appl = yf.Ticker('AAPL')

In [11]:
days = 20
hist = appl.history(period=f'{days}d')
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-01-30 00:00:00-05:00,190.696667,191.555572,187.231088,187.800354,55859400,0.00,0.0
2024-01-31 00:00:00-05:00,186.801628,186.861565,184.115069,184.164993,55467800,0.00,0.0
2024-02-01 00:00:00-05:00,183.755534,186.711754,183.585753,186.621872,64885400,0.00,0.0
2024-02-02 00:00:00-05:00,179.630787,187.091269,179.021564,185.613159,102518000,0.00,0.0
2024-02-05 00:00:00-05:00,187.910213,189.008818,185.603160,187.440811,69668800,0.00,0.0
2024-02-06 00:00:00-05:00,186.621869,189.068743,186.531987,189.058762,43490800,0.00,0.0
2024-02-07 00:00:00-05:00,190.397053,190.806534,188.369641,189.168625,53439000,0.00,0.0
2024-02-08 00:00:00-05:00,189.148646,189.298448,187.111252,188.080017,40962000,0.00,0.0
2024-02-09 00:00:00-05:00,188.649994,189.990005,188.000000,188.850006,45155200,0.24,0.0
2024-02-12 00:00:00-05:00,188.419998,188.669998,186.789993,187.149994,41781900,0.00,0.0
2024-02-13 00:00:00-05:00,185.770004,186.210007,183.509995,185.039993,56529500,0.00,0.0
2024-02-14 00:00:00-05:00,185.320007,185.529999,182.440002,184.149994,54630500,0.00,0.0
2024-02-15 00:00:00-05:00,183.550003,184.490005,181.350006,183.860001,65434500,0.00,0.0
2024-02-16 00:00:00-05:00,183.419998,184.850006,181.669998,182.309998,49701400,0.00,0.0
2024-02-20 00:00:00-05:00,181.789993,182.429993,180.000000,181.559998,53665600,0.00,0.0
2024-02-21 00:00:00-05:00,181.940002,182.889999,180.660004,182.320007,41529700,0.00,0.0
2024-02-22 00:00:00-05:00,183.479996,184.960007,182.460007,184.369995,52292200,0.00,0.0
2024-02-23 00:00:00-05:00,185.009995,185.039993,182.229996,182.520004,45074500,0.00,0.0
2024-02-26 00:00:00-05:00,182.240005,182.759995,180.649994,181.160004,40867400,0.00,0.0
2024-02-27 00:00:00-05:00,181.100006,183.919998,179.559998,182.630005,54219400,0.00,0.0